trigger: none

variables:
- group: PSACTION1_SIGNATURE

resources:
  repositories:
    - repository: self
      type: github
      name: Action1Corp/PSAction1
      endpoint: 'Action1 GitHub'
      branch: 'main'

pool:
  vmImage: 'windows-latest'

jobs:
- job: SignScripts
  displayName: 'Sign scripts'
  steps:

    - checkout: self
      clean: true
      fetchDepth: 0
      persistCredentials: true

    - task: PowerShell@2
      displayName: 'Sign PowerShell Files'
      inputs:
        targetType: inline
        script: |
          Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Include *.ps1, *.psm1, *.-File |
            ForEach-Object {
                  $filePath = "$($_.FullName)"
                  $fileBaseName = (Get-Item $filePath).BaseName
                  $fileExtension = (Get-Item $filePath).Extension
                  $signedFilePath = Join-Path -Path "$(Build.ArtifactStagingDirectory)" -ChildPath "$fileBaseName.$fileExtension"
                  Copy-Item -Path $filePath -Destination $signedFilePath
            }

    - task: TrustedSigning@0
      inputs:
        AzureTenantID: '$(AZURE_TENANT_ID)'
        AzureClientID: '$(AZURE_CLIENT_ID)'
        AzureClientSecret: '$(AZURE_CLIENT_SECRET)'
        Endpoint: '$(AZURE_TS_ENDPOINT)'
        TrustedSigningAccountName: '$(AZURE_TS_ACCOUNT_NAME)'
        CertificateProfileName: '$(AZURE_TS_CERTIFICATE_PROFILE_NAME)'
        FilesFolder: '$(Build.ArtifactStagingDirectory)'
        FileDigest: 'SHA256'
      env:
        AZURE_CLIENT_ID: $(AZURE_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
        AZURE_TENANT_ID: $(AZURE_TENANT_ID)
        AZURE_TS_ENDPOINT: $(AZURE_TS_ENDPOINT)
        AZURE_TS_ACCOUNT_NAME: $(AZURE_TS_ACCOUNT_NAME)
        AZURE_TS_CERTIFICATE_PROFILE_NAME: $(AZURE_TS_CERTIFICATE_PROFILE_NAME)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Internally'
      condition: always()
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'release'
        publishLocation: 'Container'
