trigger: none

resources:
  repositories:
    - repository: self
      type: github
      name: Action1Corp/PSAction1
      endpoint: 'Action1 GitHub'
      branch: 'main'

pool:
  vmImage: 'windows-latest'

jobs:
- job: SignScripts
  displayName: 'Sign scripts'
  steps:

    - checkout: self
      clean: true
      fetchDepth: 0
      persistCredentials: true

    - task: PowerShell@2
      displayName: 'Display checked-out files'
      inputs:
        targetType: inline
        script: |
          Write-Host "Checked out main branch"
          Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse