trigger: none

resources:
  repositories:
    - repository: self
      type: github
      name: Action1Corp/PSAction1
      endpoint: 'Action1 GitHub'
      branch: 'main'

pool:
  vmImage: 'windows-latest'

jobs:
- job: SignScripts
  displayName: 'Sign scripts'
  steps:

    - checkout: self
      clean: true
      fetchDepth: 0
      persistCredentials: true

    - task: AWSShellScript@1
      displayName: 'Get codesign cert'
      inputs:
        awsCredentials: 'Action1 AWS'
        regionName: 'us-east-1'
        scriptType: 'inline'
        inlineScript: |
          $secret = aws secretsmanager get-secret-value --secret-id a1-builder/codesigncert --query SecretString --output text | ConvertFrom-Json
          $pfxbase64 = $secret.codesigncert
          $pfxdata = [System.Convert]::FromBase64String($pfxbase64)
          [IO.File]::WriteAllBytes("$($env:BUILD_SOURCESDIRECTORY)\cert.pfx", $pfxdata)
    
    - task: PowerShell@2
      displayName: 'Display sources directory files'
      inputs:
        targetType: inline
        script: |
          Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse